name: sea-ice-oscillations
channels:
  - conda-forge
dependencies:
  - ipykernel
  - xarray
  - cf_xarray
  - xarray-datatree
  - satpy
  - sentinelsat
  # - opticalflow
  - py-opencv
  - openpiv
  - scikit-image
  - matplotlib-base
  - earthaccess
  - hvplot
  - geoviews
  - descartes
  - pandas
  - cartopy
  - fiona
  - shapely
  - geopandas
  - netcdf4
  - h5netcdf
  - h5py
  - xesmf
  - esmf=8.2.0
  - esmpy=8.2.0
  - pip
  - pip:
      - flowpy
