name: process-viirs-images
channels:
  - conda-forge
dependencies:
  - ipykernel
  - xarray
  - cf_xarray
  - xarray-datatree
  - satpy
  - sentinelsat
  - scikit-image
  - matplotlib-base
  - earthaccess
  - hvplot
  - geoviews
  - descartes
  - pandas
  - cartopy
  - fiona
  - shapely
  - geopandas
  - netcdf4
  - h5netcdf
  - h5py
  - xesmf
  - pip
  - pip:
      - flowpy
